### ISSUE TITLE
Authentication always fails

### ISSUE THREAD

**Issue by deerflow** [GitbookIO/node-gitbook-api#11]
Environment :
- Node.js 14.16.0
- gitbook-api 2.1.3

Description :
Authentication always fails (tried with 2 different accounts and tokens)

Steps to reproduce :
- Create a JS file with :
```javascript
const GitBookAPI = require('gitbook-api');

const client = new GitBookAPI({
  username: 'USERNAME',
  token: 'TOKEN'
})

client.get('/user/spaces')
  .then(res => console.log(res))
  .catch(e => console.error(e));
```
- Run the file

Stacktrace :
```
Error: Authentication has failed (Invalid user, password or access token)
    at Request._callback (/Users/florian/Documents/dev/gitbook-test/node_modules/gitbook-api/lib/index.js:79:23)
    at Request.self.callback (/Users/florian/Documents/dev/gitbook-test/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/florian/Documents/dev/gitbook-test/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:327:22)
    at IncomingMessage.<anonymous> (/Users/florian/Documents/dev/gitbook-test/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  statusCode: 401,
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.gitbook.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.gitbook.com',
      _readableState: [ReadableState],
      _maxListeners: 0,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 6,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      connection: 'close',
      date: 'Mon, 12 Jul 2021 11:55:05 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '89',
      'x-frame-options': 'SAMEORIGIN',
      server: 'GitBook.com',
      'x-pjax-url': '/api/user/spaces',
      'x-pjax-version': '24.0.0',
      'access-control-allow-credentials': 'true',
      'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
      'access-control-max-age': '86400',
      'access-control-allow-headers': 'Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, X-GitHub-OTP, X-Requested-With',
      'access-control-allow-methods': 'GET, HEAD, POST, PATCH, PUT, DELETE',
      'access-control-allow-origin': '*',
      'cache-control': 'no-store, must-revalidate',
      pragma: 'no-cache',
      expires: '0',
      etag: 'W/"59-iq+X0rYkSRJy6/ck5uNZ3EtFNF8"',
      'set-cookie': [Array],
      via: '1.1 vegur'
    },
    rawHeaders: [
      'Connection',
      'close',
      'Date',
      'Mon, 12 Jul 2021 11:55:05 GMT',
      'Content-Type',
      'application/json; charset=utf-8',
      'Content-Length',
      '89',
      'X-Frame-Options',
      'SAMEORIGIN',
      'Server',
      'GitBook.com',
      'X-Pjax-Url',
      '/api/user/spaces',
      'X-Pjax-Version',
      '24.0.0',
      'Access-Control-Allow-Credentials',
      'true',
      'Access-Control-Expose-Headers',
      'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
      'Access-Control-Max-Age',
      '86400',
      'Access-Control-Allow-Headers',
      'Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, X-GitHub-OTP, X-Requested-With',
      'Access-Control-Allow-Methods',
      'GET, HEAD, POST, PATCH, PUT, DELETE',
      'Access-Control-Allow-Origin',
      '*',
      'Cache-Control',
      'no-store, must-revalidate',
      'Pragma',
      'no-cache',
      'Expires',
      '0',
      'Etag',
      'W/"59-iq+X0rYkSRJy6/ck5uNZ3EtFNF8"',
      'Set-Cookie',
      'gitbook:sess=eyJ2YXJpYW50IjoxLCJhbm9ueW1vdXNJZCI6ImZmODYzODgxLWViM2UtNGMxNS1iOTFjLTUzNGEzYmYxZWZmOSJ9; path=/; expires=Wed, 11 Aug 2021 11:55:05 GMT; secure; httponly',
      'Set-Cookie',
      'gitbook:sess.sig=DsaIF_f4R6Em1uI9jirziiihVH0; path=/; expires=Wed, 11 Aug 2021 11:55:05 GMT; secure; httponly',
      'Via',
      '1.1 vegur'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 401,
    statusMessage: 'Unauthorized',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.gitbook.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.gitbook.com',
      _readableState: [ReadableState],
      _maxListeners: 0,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 6,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
```

**Comment by hughrawlinson** [comment]
Hey @deerflow, sorry for the confusion here - this wrapper library is for a previous version of the GitBook API that is no longer supported. The current API is documented [here](https://developer.gitbook.com/), and there isn't a Javascript wrapper for it right now. We'll consider releasing one in the future, but for now it's best to make the http requests directly, and using auth as described in the docs.

We should absolutely make this clear in the repo and in the npm page, I'll see about doing that ASAP.

That said, I was able to get this library to query the current API successfully. If you provide a username, this library tries to use Basic auth which is no longer supported. But, if you provide an account object that doesn't contain a username, the library will use Bearer auth, which is supported. Additionally, you will have to provide a config object containing the API host as shown below.

```js
const GitBookAPI = require('gitbook-api');
const client = new GitBookAPI({
	token: process.env.GITBOOK_API_TOKEN
}, {host: 'https://api-beta.gitbook.com'});

client.get(`/v1/user`).then((result) => {
	console.log(result);
});
```

I would definitely recommend taking into account that this API is in beta and therefore it's subject to change without notice.

I'm interested in hearing about your use case though - if you're happy to share, what are you hoping to accomplish with the API?
